bank/urls.py
from django.urls import path, include
from .api import GetAccount, TransferMoney, RollbackTransaction

from . import views

app_name = "bank"

urlpatterns = [
    path("", views.index, name="index"),
    path("index-employee.html", views.employee_index, name="employee_index"),
    path("loan/", views.get_loan, name="loan"),
    path(
        "bank_to_bank_transfer/",
        views.bank_to_bank_transfer,
        name="bank_to_bank_transfer",
    ),
    path("transfer_money/", views.transfer_money, name="transfer_money"),
    path("internal_transfer/", views.internal_transfer, name="internal_transfer"),
    path("account_details/<int:pk>/", views.account_details, name="account_details"),
    path("customer_details/<int:pk>/", views.customer_details, name="customer_details"),
    path("api/v1/get-account/", GetAccount.as_view()),
    path("api/v1/transfer/", TransferMoney.as_view()),
    path("api/v1/rollback-transaction/", RollbackTransaction.as_view()),
    path("api/v1/rest-auth/", include("dj_rest_auth.urls")),
]

login/urls.py
from django.urls import path
from . import views

app_name = "login"

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login, name="login"),
    path("sign_up/", views.sign_up, name="sign_up"),
    path("logout/", views.logout, name="logout"),
    path(
        "request_password_reset/",
        views.request_password_reset,
        name="request_password_reset",
    ),
    path("password_reset/", views.password_reset, name="password_reset"),
    path(
        "add_authentication/<int:user>/",
        views.add_authentication,
        name="add_authentication",
    ),
    path(
        "authenticate_user/<int:user>/",
        views.authenticate_user,
        name="authenticate_user",
    ),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("login.urls")),
    path("bank/", include("bank.urls")),
]

login/models.py
from xmlrpc.client import boolean
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db.models.query import QuerySet
from bank.models import Account, Ledger
from secrets import token_urlsafe


class Profile(models.Model):
    BASIC = "basic"
    SILVER = "silver"
    GOLD = "gold"

    RANKS = [
        (BASIC, "Basic"),
        (SILVER, "Silver"),
        (GOLD, "Gold"),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.IntegerField(default=12345)
    customer_rank = models.CharField(choices=RANKS, default=BASIC, max_length=6)
    topt_identity = models.CharField(max_length=64, null=True)

    @property
    def full_name(self) -> str:
        return f"{self.user.first_name} {self.user.last_name}"

    @property
    def is_customer(self) -> boolean:
        return self.user.is_staff

    @property
    def accounts(self) -> QuerySet:
        return Account.objects.filter(user=self.user)

    @property
    def default_account(self) -> Account:
        return Account.objects.filter(user=self.user).first()

    @property
    def can_take_loan(self) -> boolean:
        if self.customer_rank == "silver" or self.customer_rank == "gold":
            return True
        else:
            return False

    @classmethod
    def take_loan(cls, customer, credit_account, credit_text, amount, loan_name):
        assert amount >= 0, "Negative amount not allowed for loan."
        assert cls.can_take_loan, "User rank does not allow for making loans."

        loan_account = Account.objects.create(
            user=customer, account_name=loan_name, is_loan=True
        )

        Ledger.transfer(
            amount=amount,
            debit_account=loan_account,
            debit_text="New loan",
            credit_account=credit_account,
            credit_text=credit_text,
            is_loan=True,
        )

    def __str__(self):
        return f"{self.user.username}"


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class PasswordResetRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=43, default=token_urlsafe)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    updated_timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user} - {self.created_timestamp} - {self.updated_timestamp} - {self.token}"

login/views.py
from django.shortcuts import render, reverse
from .models import PasswordResetRequest
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout
from django.http import HttpResponseRedirect
import environ
from twilio.rest import Client
import pyqrcode
import django_rq
from .messaging import email_message
import uuid


def index(request):
    return render(request, "login/index.html")


def login(request):
    context = {}

    if request.method == "POST":
        if "login" in request.POST:
            try:
                user = authenticate(
                    request,
                    username=request.POST["user"],
                    password=request.POST["password"],
                )

                return HttpResponseRedirect(
                    reverse("login:authenticate_user", kwargs={"user": user.pk})
                )
            except Exception:
                context = {"error": "Bad username or password."}

    return render(request, "login/login.html", context)


def logout(request):
    dj_logout(request)
    return HttpResponseRedirect(reverse("login:login"))


def sign_up(request):
    context = {}
    env = environ.Env()
    environ.Env.read_env()
    account_sid = env("TWILIO_ACCOUNT_SID")
    auth_token = env("TWILIO_AUTH_TOKEN")
    service_sid = env("TWILIO_SERVICE_SID")
    client = Client(account_sid, auth_token)

    if request.method == "POST":
        if "signup" in request.POST:
            password = request.POST["password"]
            confirm_password = request.POST["confirm_password"]
            user_name = request.POST["user"]
            phone_number = request.POST["phone_number"]
            email = request.POST["email"]

            if password == confirm_password:
                enitity_id = uuid.uuid4()
                user = User.objects.create_user(user_name, email, password)
                user.profile.phone_number = phone_number
                user.is_staff = True if request.POST["is_staff"] == "yes" else False
                user.profile.topt_identity = enitity_id

                try:
                    user.save()
                    new_factor = (
                        client.verify.services(service_sid)
                        .entities(enitity_id)
                        .new_factors.create(
                            friendly_name=f"{user_name}'s account", factor_type="totp"
                        )
                    )
                    factor_obj = new_factor.binding
                    url = pyqrcode.create(factor_obj["uri"])
                    url.svg("login/static/login/authy-url.svg", scale=2)

                    return HttpResponseRedirect(
                        reverse("login:add_authentication", kwargs={"user": user.pk})
                    )
                except Exception:
                    context = {
                        "error": "Could not create user account - please try again."
                    }
            else:
                context = {"error": "Passwords did not match. Please try again."}

    return render(request, "login/sign_up.html", context)


def add_authentication(request, user):
    context = {}
    user = User.objects.get(pk=user)
    env = environ.Env()
    environ.Env.read_env()
    account_sid = env("TWILIO_ACCOUNT_SID")
    auth_token = env("TWILIO_AUTH_TOKEN")
    service_sid = env("TWILIO_SERVICE_SID")
    client = Client(account_sid, auth_token)

    if request.method == "POST":
        if "register_authenticate" in request.POST:
            register_topt_code = request.POST["register_topt_code"]
            print(register_topt_code)
            factors = (
                client.verify.services(service_sid)
                .entities(user.profile.topt_identity)
                .factors.list(limit=20)
            )

            for record in factors:
                user_factor = record.sid

            factor = (
                client.verify.services(service_sid)
                .entities(user.profile.topt_identity)
                .factors(user_factor)
                .update(auth_payload=register_topt_code)
            )

            if factor.status == "verified":
                return HttpResponseRedirect(reverse("login:login"))
            else:
                context = {"error": "Wrong code, please try again"}

    return render(request, "login/add_authentication.html", context)


def authenticate_user(request, user):
    context = {}
    user = User.objects.get(pk=user)
    env = environ.Env()
    environ.Env.read_env()
    account_sid = env("TWILIO_ACCOUNT_SID")
    auth_token = env("TWILIO_AUTH_TOKEN")
    service_sid = env("TWILIO_SERVICE_SID")
    client = Client(account_sid, auth_token)

    factors = (
        client.verify.services(service_sid)
        .entities(user.profile.topt_identity)
        .factors.list(limit=20)
    )

    for record in factors:
        user_factor = record.sid

    if request.method == "POST":
        if "authenticate" in request.POST:
            topt_code = request.POST["topt_code"]

            challenge = (
                client.verify.services(service_sid)
                .entities(user.profile.topt_identity)
                .challenges.create(auth_payload=topt_code, factor_sid=user_factor)
            )

            if challenge.status == "approved":
                dj_login(request, user)
                return HttpResponseRedirect(
                    reverse(
                        "bank:employee_index"
                        if request.user.is_staff is True
                        else "bank:index"
                    )
                )
            else:
                context = {"error": "Wrong code, please try again"}

    return render(request, "login/authenticate.html", context)


def request_password_reset(request):
    if request.method == "POST":
        post_user = request.POST["username"]
        user = None

        if post_user:
            try:
                user = User.objects.get(username=post_user)
            except Exception:
                print(f"Invalid password request: {post_user}")
        else:
            post_user = request.POST["email"]
            try:
                user = User.objects.get(email=post_user)
            except Exception:
                print(f"Invalid password request: {post_user}")
        if user:
            prr = PasswordResetRequest()
            prr.user = user
            prr.save()
            django_rq.enqueue(
                email_message,
                {
                    "token": prr.token,
                    "email": prr.user.email,
                },
            )
            return HttpResponseRedirect(reverse("login:password_reset"))

    return render(request, "login/request_password_reset.html")


def password_reset(request):
    if request.method == "POST":
        password = request.POST["password"]
        confirm_password = request.POST["confirm_password"]
        token = request.POST["token"]

        if password == confirm_password:
            try:
                prr = PasswordResetRequest.objects.get(token=token)
                prr.save()
            except Exception:
                print("Invalid password reset attempt.")
                return render(request, "login/password_reset.html")

            user = prr.user
            user.set_password(password)
            user.save()
            return HttpResponseRedirect(reverse("login:login"))

    return render(request, "login/password_reset.html")

login/templates/login/add_authentication.html
{% extends "login/base.html" %} {% block content %}
<section id="add_authentication" class="skew_background">
  <h1>Two factor authentication</h1>
  <p>Scan the QR code and add your account to your preferred authenticator app</p>
  {% load static %}
  <div class="qrcode_container">
    <img height="auto" width="auto" src="{% static 'login/authy-url.svg' %}" alt="qr code" />
  </div>

  <p>Then enter your authentication code below.</p>
  <form action="." method="POST">
    {% csrf_token %}
    <input type="number" name="register_topt_code" id="register_topt_code" placeholder="Authenticator code" />
    <button class="button" type="submit" name="register_authenticate">Submit</button>
  </form>
  {% if error %} {{ error }} {% endif %}
</section>
{% endblock %}

login/templates/login/authenticate.html
{% extends "login/base.html" %} {% block content %}
<section id="authentication" class="skew_background">
  <h1>Two factor authentication</h1>
  <p>Enter your authentication code below.</p>
  <form action="." method="POST">
    {% csrf_token %}
    <input type="number" name="topt_code" id="topt_code" placeholder="Authenticator code" />
    <button class="button" type="submit" name="authenticate">Continue</button>
  </form>
  {% if error %} {{ error }} {% endif %}
</section>

{% endblock %}

login/templates/login/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Kea bank" />
    <meta name="keywords" content="bank, kea" />
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}" media="screen" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;1,200;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet" />
    <title>KEA Bank</title>
  </head>
  <body>
    <div class="topbar">
      <a href="{% url 'login:index' %}">
        <img src="{% static 'login/logo.svg' %}" alt="keabanklogo" srcset="" />
      </a>
    </div>

    {% block content %} {% endblock %} {% block footer %} {% endblock %}
  </body>
</html>

login/templates/login/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="keywords" content="bank, kea" />
    <meta name="description" content="Kea bank" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}" media="screen" />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;1,200;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet" />
    <title>KEA Bank</title>
  </head>
  <body>
    <div class="topbar">
      <a href="{% url 'login:index' %}">
        <img src="{% static 'login/logo.svg' %}" alt="keabanklogo" srcset="" />
      </a>
    </div>
    <section id="homepage" class="skew_background">
      <div class="column">
        <h1>KEA Bank</h1>
        <p>Join the best bank in the world!</p>
        <div class="button_container">
          <a class="button" href="{% url 'login:sign_up' %}"
            ><span class="icon"><img src="{% static 'login/signup.svg' %}" alt="" srcset="" /></span> Sign Up</a
          >
          <a class="button" href="{% url 'login:login' %}"
            ><span><img src="{% static 'login/login.svg' %}" alt="" srcset="" /></span><span>Login</span>
          </a>
        </div>
      </div>
      <div class="column">
        <img src="{% static 'login/keabankcover.svg' %}" alt="" srcset="" />
      </div>
    </section>
  </body>
</html>

login/templates/login/login.html
{% extends "login/base.html" %} {% block content %}
<section id="login" class="skew_background">
  <div class="column">
    <h1>Login</h1>
    <form action="." method="POST">
      {% csrf_token %}
      <input type="text" name="user" placeholder="User Name" />
      <input type="password" name="password" placeholder="Password" />
      <button name="login" class="button">Login</button>
    </form>
    {% if error %} {{ error }} {% endif %} {% load static %}
    <!-- <span class="qrcode_container">
      <img class="qrcode" src="{% static 'login/authy-url.svg' %}" alt="qr code" />
    </span> -->
    <span>Forgot your password?</span>
    <a href="{% url 'login:request_password_reset' %}">Reset your password here</a>
    <span>Don't have an account?</span>
    <a href="{% url 'login:sign_up' %}">Sign up here</a>
  </div>
  <div class="column">
    {% load static %}
    <img src="{% static 'login/keabankcover.svg' %}" alt="" srcset="" />
  </div>
</section>

{% endblock %}

login/templates/login/password_reset.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Kea bank" />
    <meta name="keywords" content="bank, kea" />
    <title>Reset Password</title>
  </head>
  <body>
    <h1>Reset Password</h1>
    <hr />
    <form action="{% url 'login:password_reset' %}" method="POST">
      {% csrf_token %}
      <input type="text" name="username" placeholder="User Name" />
      <br />
      <input type="password" name="password" placeholder="New Password" />
      <br />
      <input type="password" name="confirm_password" placeholder="Repeat New Password" />
      <br />
      <input type="text" name="token" placeholder="Token" />
      <br />
      <button>Submit</button>
    </form>
    <hr />
  </body>
</html>

login/templates/login/request_password_reset.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Kea bank" />
    <meta name="keywords" content="bank, kea" />
    <title>Request Password Reset</title>
  </head>
  <body>
    <h1>Request Password Reset</h1>
    <hr />
    <form action="{% url 'login:request_password_reset' %}" method="POST">
      {% csrf_token %}
      <input type="text" name="username" placeholder="User Name" />
      <br />
      <input type="email" name="email" placeholder="Email Address" />
      <br />
      <button>Submit</button>
    </form>
    <hr />
  </body>
</html>

login/templates/login/sign_up.html
{% extends "login/base.html" %} {% block content %}
<section id="signup" class="skew_background">
  <div class="column">
    <h1>Sign Up</h1>
    <form action="." method="POST">
      {% csrf_token %}
      <input type="text" name="user" placeholder="User Name" />
      <input type="email" name="email" placeholder="Email Address" />
      <input type="text" name="phone_number" placeholder="Phone number" />
      <input type="password" name="password" placeholder="Password" />
      <input type="password" name="confirm_password" placeholder="Confirm Password" />
      <label for="is_staff">Is employee?</label>
      <select name="is_staff" id="is_staff">
        <option value="yes">Yes</option>
        <option value="no">No</option>
      </select>
      <button name="signup" class="button">Sign Up</button>
    </form>
    {% if error %} {{ error }} {% endif %}

    <a href="{% url 'login:login' %}">Login instead</a>
  </div>
  <div class="column">
    {% load static %}
    <img src="{% static 'login/keabankcover.svg' %}" alt="" srcset="" />
  </div>
</section>

{% endblock %}