bank/urls.py
from django.urls import path, include
from .api import GetAccount, TransferMoney, RollbackTransaction

from . import views

app_name = "bank"

urlpatterns = [
    path("", views.index, name="index"),
    path("index-employee.html", views.employee_index, name="employee_index"),
    path("loan/", views.get_loan, name="loan"),
    path(
        "bank_to_bank_transfer/",
        views.bank_to_bank_transfer,
        name="bank_to_bank_transfer",
    ),
    path("transfer_money/", views.transfer_money, name="transfer_money"),
    path("internal_transfer/", views.internal_transfer, name="internal_transfer"),
    path("account_details/<int:pk>/", views.account_details, name="account_details"),
    path("customer_details/<int:pk>/", views.customer_details, name="customer_details"),
    path("api/v1/get-account/", GetAccount.as_view()),
    path("api/v1/transfer/", TransferMoney.as_view()),
    path("api/v1/rollback-transaction/", RollbackTransaction.as_view()),
    path("api/v1/rest-auth/", include("dj_rest_auth.urls")),
]

login/urls.py
from django.urls import path
from . import views

app_name = "login"

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login, name="login"),
    path("sign_up/", views.sign_up, name="sign_up"),
    path("logout/", views.logout, name="logout"),
    path(
        "request_password_reset/",
        views.request_password_reset,
        name="request_password_reset",
    ),
    path("password_reset/", views.password_reset, name="password_reset"),
    path(
        "add_authentication/<int:user>/",
        views.add_authentication,
        name="add_authentication",
    ),
    path(
        "authenticate_user/<int:user>/",
        views.authenticate_user,
        name="authenticate_user",
    ),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("login.urls")),
    path("bank/", include("bank.urls")),
]

bank/models.py
from django.db import models, transaction
from django.contrib.auth.models import User
from django.db.models.query import QuerySet
from decimal import Decimal
import datetime
from .errors import InsufficientFunds
import uuid

# Celery
import json
from django.utils import timezone
from django_enum_choices.fields import EnumChoiceField
from django_celery_beat.models import IntervalSchedule, PeriodicTask
from .enums import TimeInterval, SetupStatus


def random_id():
    return "DK-" + str(uuid.uuid4())


class Account(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    account_name = models.CharField(max_length=40)
    is_loan = models.BooleanField(default=False)
    account_id = models.CharField(default=random_id, max_length=100)

    @property
    def movements(self) -> QuerySet:
        return Ledger.objects.filter(account=self)

    @property
    def balance(self) -> Decimal:
        return self.movements.aggregate(models.Sum("amount"))["amount__sum"] or Decimal(
            0
        )

    def __str__(self):
        return f"{self.user} :: {self.account_name} :: {self.pk}"


class Ledger(models.Model):
    transaction_id = models.CharField(max_length=100)
    account = models.ForeignKey(Account, null=True, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    text = models.CharField(max_length=100)
    date = models.DateField(default=datetime.date.today)

    @classmethod
    def transfer(
        cls,
        amount,
        debit_account,
        debit_text,
        credit_account,
        credit_text,
        is_loan=False,
    ) -> int:
        assert amount >= 0, "Negative amount not allowed for transfer."
        with transaction.atomic():
            if debit_account.balance >= amount or is_loan:
                id = uuid.uuid4()
                # cls is the Ledger object
                cls(
                    transaction_id=id,
                    account=credit_account,
                    amount=amount,
                    text=credit_text,
                ).save()
                cls(
                    transaction_id=id,
                    account=debit_account,
                    amount=-amount,
                    text=debit_text,
                ).save()
                print("transaction complete")
            else:
                raise InsufficientFunds
        return id

    @classmethod
    def bank_to_bank_transfer(
        cls,
        amount,
        debit_account,
        debit_text,
        credit_account,
        credit_text,
        transaction_id,
    ) -> int:
        assert amount >= 0, "Negative amount not allowed for transfer."
        with transaction.atomic():
            if debit_account.balance >= amount:
                cls(
                    transaction_id=transaction_id,
                    account=credit_account,
                    amount=amount,
                    text=credit_text,
                ).save()
                cls(
                    transaction_id=transaction_id,
                    account=debit_account,
                    amount=-amount,
                    text=debit_text,
                ).save()
                print("transaction complete")
            else:
                raise InsufficientFunds
        return transaction_id

    def __str__(self):
        return f"{self.amount} :: {self.transaction_id} :: {self.date} :: {self.account} :: {self.text}"


class ScheduledPayment(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=70, blank=False)
    status = EnumChoiceField(SetupStatus, default=SetupStatus.active)
    created_at = models.DateTimeField(auto_now_add=True)
    time_interval = EnumChoiceField(TimeInterval, default=TimeInterval.one_min)
    from_account = models.ForeignKey(
        Account, related_name="FromAccount", null=True, on_delete=models.CASCADE
    )
    to_account = models.ForeignKey(
        Account, related_name="ToAccount", null=True, on_delete=models.CASCADE
    )
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    text = models.CharField(max_length=100)
    text2 = models.CharField(max_length=100)

    task = models.OneToOneField(
        PeriodicTask, on_delete=models.CASCADE, null=True, blank=True
    )

    def delete(self, *args, **kwargs):
        if self.task is not None:
            self.task.delete()

        return super(self.__class__, self).delete(*args, **kwargs)

    def setup_task(self):

        self.task = PeriodicTask.objects.create(
            name=self.title,
            task="sp_task",
            interval=self.interval_schedule,
            args=json.dumps([self.id]),
            start_time=timezone.now(),
        )
        self.save()

    @property
    def interval_schedule(self):
        if self.time_interval == TimeInterval.one_min:
            return IntervalSchedule.objects.get(every=1, period="minutes")
        if self.time_interval == TimeInterval.five_mins:
            return IntervalSchedule.objects.get(every=5, period="minutes")
        if self.time_interval == TimeInterval.one_hour:
            return IntervalSchedule.objects.get(every=1, period="hours")

        raise NotImplementedError(
            """Interval Schedule for {interval} is not added.""".format(
                interval=self.time_interval.value
            )
        )

    def __str__(self):
        return f"{self.user} :: {self.title} "

bank/views.py
from django.shortcuts import render
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import Account, Ledger, ScheduledPayment
from login.models import Profile
from .enums import SetupStatus
import uuid
import requests
from twilio.rest import Client
import environ
from datetime import datetime


@login_required
def index(request):
    logged_in_user = request.user
    accounts = Account.objects.filter(user=logged_in_user)
    scheduled_payments = ScheduledPayment.objects.filter(user=logged_in_user)
    context = {"accounts": accounts, "scheduled_payments": scheduled_payments}

    if request.method == "POST":

        if "add_scheduled_payment" in request.POST:
            scheduled_payment = ScheduledPayment()
            scheduled_payment.title = request.POST["scheduled_payment_title"]
            scheduled_payment.user = logged_in_user
            scheduled_payment.created_at = datetime
            scheduled_payment.from_account = accounts.get(
                pk=request.POST["sp_accounts"]
            )
            scheduled_payment.to_account = accounts.get(pk=request.POST["sp_accounts2"])
            scheduled_payment.amount = int(request.POST["scheduled_payment_amount"])
            scheduled_payment.text = request.POST["sp_text"]
            scheduled_payment.text2 = request.POST["sp_text2"]
            scheduled_payment.save()
            scheduled_payment.setup_task()
            scheduled_payment.task.enabled = (
                scheduled_payment.status == SetupStatus.active
            )
            scheduled_payment.task.save()

        elif "create_account" in request.POST:
            account = Account()
            account.account_name = request.POST["account_name"]
            account.user = logged_in_user
            account.save()

    return render(request, "bank/index.html", context)


@login_required
def employee_index(request):
    all_customers = User.objects.filter(is_staff=False)
    context = {"customers": all_customers}

    if request.method == "POST":
        password = request.POST["password"]
        confirm_password = request.POST["confirm_password"]
        user_name = request.POST["user"]
        phone_number = request.POST["phone_number"]
        email = request.POST["email"]

        if password == confirm_password:
            user = User.objects.create_user(user_name, email, password)
            user.profile.phone_number = phone_number
            user.is_staff = False
            try:
                user.save()
                context = {"message": "Customer created", "customers": all_customers}
            except IntegrityError:
                context = {
                    "error": "Could not create customer",
                    "customers": all_customers,
                }
                # laga þetta, finna ut hvernig að maður lætur síðuna ekki sýna allan errorinn
                raise Exception("Could not create customer")
        else:
            context = {
                "error": "Passwords did not match. Please try again.",
                "customers": all_customers,
            }

    return render(request, "bank/index-employee.html", context)


@login_required
def account_details(request, pk):

    account = Account.objects.get(pk=pk)
    context = {"account": account}

    return render(request, "bank/account-details.html", context)


@login_required
def customer_details(request, pk):

    customer = User.objects.get(pk=pk)
    profile = Profile.objects.get(user=customer)
    customer_accounts = Account.objects.filter(user=customer)

    context = {
        "customer": customer,
        "profile": profile,
        "customer_accounts": customer_accounts,
    }

    if request.method == "POST":
        if "change_rank" in request.POST:
            new_rank = request.POST["rank"]
            print(profile.customer_rank)
            profile.customer_rank = new_rank
            profile.save()

        if "create_customer_account" in request.POST:
            account = Account()
            account.account_name = request.POST["account_name"]
            account.user = customer
            account.save()

    return render(request, "bank/customer-details.html", context)


@login_required
def transaction_details(request):
    pass


@login_required
def get_loan(request):
    context = {}
    logged_in_user = request.user
    accounts = Account.objects.filter(user=logged_in_user)
    context = {"accounts": accounts}

    if request.method == "POST":

        if "make_loan" in request.POST:
            to_loan_account = accounts.get(pk=request.POST["accounts3"])
            from_transfer_text = request.POST["loan_text"]
            loan_amount = int(request.POST["loan_amount"])
            loan_name = request.POST["loan_name"]

            Profile.take_loan(
                logged_in_user,
                to_loan_account,
                from_transfer_text,
                loan_amount,
                loan_name,
            )

    return render(request, "bank/loan.html", context)


# transfer money between your own accounts
@login_required
def transfer_money(request):
    context = {}
    logged_in_user = request.user
    accounts = Account.objects.filter(user=logged_in_user)
    context = {"accounts": accounts}

    if request.method == "POST":
        if "transfer_money" in request.POST:
            from_account = accounts.get(pk=request.POST["accounts"])
            to_account = accounts.get(pk=request.POST["accounts2"])
            from_transfer_text = request.POST["transfer_text"]
            to_transfer_text2 = request.POST["transfer_text2"]
            transfer_amount = int(request.POST["transfer_amount"])

            Ledger.transfer(
                transfer_amount,
                from_account,
                from_transfer_text,
                to_account,
                to_transfer_text2,
            )

    return render(request, "bank/transfer-money.html", context)


# transfer money to another person in the same bank
@login_required
def internal_transfer(request):
    context = {}
    logged_in_user = request.user
    accounts = Account.objects.filter(user=logged_in_user)
    context = {"accounts": accounts}

    if request.method == "POST":
        if "internal_transfer_money" in request.POST:
            accounts = Account.objects.all()
            from_account = accounts.get(pk=request.POST["from_internal_account"])
            to_account_id = request.POST["to_internal_account"]
            from_transfer_text = request.POST["internal_transfer_text"]
            to_transfer_text2 = request.POST["internal_transfer_text2"]
            transfer_amount = int(request.POST["internal_transfer_amount"])

            env = environ.Env()
            environ.Env.read_env()
            account_sid = env("TWILIO_ACCOUNT_SID")
            auth_token = env("TWILIO_AUTH_TOKEN")
            client = Client(account_sid, auth_token)

            try:
                to_account = accounts.get(account_id=to_account_id)
                message = f"From KEA Bank. You have just recived {transfer_amount} from {request.user.username} on your account: {to_account.account_name}. Message from sender: {to_transfer_text2}"
                Ledger.transfer(
                    transfer_amount,
                    from_account,
                    from_transfer_text,
                    to_account,
                    to_transfer_text2,
                )

                message = client.messages.create(
                    from_="+4552513028",
                    body=message,
                    to=to_account.user.profile.phone_number,
                )

            except Exception:
                context = {
                    "accounts": accounts,
                    "error": "Cannot find recipient account",
                }

    return render(request, "bank/internal-transfer.html", context)


# transfer money to another person in another bank
@login_required
def bank_to_bank_transfer(request):
    context = {}
    logged_in_user = request.user
    accounts = Account.objects.filter(user=logged_in_user)
    context = {"accounts": accounts}
    all_accounts = Account.objects.all()

    if request.method == "POST":
        if "bank_transfer" in request.POST:
            internal_from_account = accounts.get(pk=request.POST["from_account"])
            account_id = request.POST["account_id"]
            amount = int(request.POST["bank_transfer_amount"])
            text = request.POST["bank_transfer_text"]
            transaction_id = uuid.uuid4()

            check_account_url = (
                "http://127.0.0.1:4000/bank/api/v1/get-account/?account_id=%s"
                % account_id
            )
            transfer_url = f"http://127.0.0.1:4000/bank/api/v1/transfer/?transaction_id={transaction_id}&amount={amount}&text={text}&account_id={account_id}"
            rollback_url = f"http://127.0.0.1:4000/bank/api/v1/rollback-transaction/?transaction_id={transaction_id}"

            account_response = requests.get(check_account_url)

            if account_response.ok:
                print("response ok")
                transfer_response = requests.post(transfer_url)
                if transfer_response.ok:
                    try:
                        bank_account = all_accounts.get(account_name="Bank IPO Account")
                        print(bank_account, "bank account")
                        Ledger.bank_to_bank_transfer(
                            amount=amount,
                            debit_account=internal_from_account,
                            debit_text=text,
                            credit_account=bank_account,
                            credit_text=text,
                            transaction_id=transaction_id,
                        )

                    except Exception:

bank/templates/bank/bank-to-bank-transfer.html
{% extends "bank/base.html" %} {% block content %}
<section id="customer_index" class="general_margin">

  <div class="tranfer-money-nav">
    <ul>
        <li><a class="button" href="{% url 'bank:index' %}">Go back</a></li>
    </ul>
  </div>  

  <div class="tranfer-money-nav">
    <ul>
        <li><a  href="{% url 'bank:transfer_money' %}">Transfer between own accounts</a></li>
        <li><a href="{% url 'bank:internal_transfer' %}">Transfer to another person</a></li>
        <li><a class="selected" href="#">Transfer to another person in another bank</a></li>
    </ul>
  </div>

  <form action="." method="POST">
    <h2>Transfer from bank to bank</h2>
    {% csrf_token %}

    <label for="from_account">From account</label>
    <select required  name="from_account" id="from_account">
      {% for account in accounts %}
      <option value="{{ account.pk }}">{{ account.account_name }}</option>
      {% endfor %}
    </select>
    <label for="bank_transfer_text">Text</label>
    <input required type="text" name="bank_transfer_text" id="bank_transfer_text" />

    <label for="bank_transfer_amount">Transfer amount</label>
    <input required type="number" name="bank_transfer_amount" id="bank_transfer_amount" />

    <label for="account_id">External Account ID</label>
    <input required type="text" name="account_id" id="account_id" />

    <button class="button" type="submit" name="bank_transfer">Bank transfer</button>
  </form>
  
</section>

{% endblock %}

bank/templates/bank/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Kea bank" />
    <meta name="keywords" content="bank, kea" />
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}" media="screen" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;1,200;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet" />
    <title>KEA Bank</title>
  </head>
  <body>
    <div class="bank_topbar">
      <a href="{% url 'login:index' %}">
        <img width="auto" height="auto" src="{% static 'login/logo.svg' %}" alt="keabanklogo" srcset="" />
      </a>
      <div class="container">
        <p>{{ user.username }}</p>
        <a href="{% url 'login:logout' %}">Log out</a>
      </div>
    </div>
    <!-- <header>
      <h1>KEA Bank</h1>
      <div class="flex">
        
        <a href="{% url 'login:logout' %}">Log out</a>
      </div>
    </header> -->

    {% block content %} {% endblock %} {% block footer %} {% endblock %}
  </body>
</html>

bank/templates/bank/customer-details.html
{% extends "bank/base.html" %} {% block content %}
<div class="general_margin">
<h3>Customer Details</h3>
<a href="{% url 'bank:employee_index' %}">Go back</a>

<table>
  <tr>
    <th>Customer username</th>
    <th>Customer rank</th>
  </tr>
  <tr>
    <td>{{ customer.username }}</td>
    <td>{{ profile.customer_rank }}</td>
  </tr>
</table>

<h3>Customer acccounts</h3>
<table>
  <tr>
    <th>Account name</th>
    <th>Account balance</th>
  </tr>
  {% for account in customer_accounts %}
  <tr>
    <td>{{ account.account_name }}</td>
    <td>{{ account.balance }}</td>
  </tr>
  {% endfor %}
</table>

<h3>Create new customer account</h3>
<form action="." method="POST">
  {% csrf_token %}
  <input type="text" name="account_name" id="account_name" placeholder="Account name" />
  <button type="submit" id="create_customer_account" name="create_customer_account">Add new customer account</button>
</form>

<h3>Change customer rank</h3>
<form action="." method="POST">
  {% csrf_token %}
  <p>Old rank: {{ profile.customer_rank }}</p>
  <p>New rank</p>
  <select name="rank" id="rank">
    <option value="basic">Basic</option>
    <option value="silver">Silver</option>
    <option value="gold">Gold</option>
  </select>
  <button type="submit" id="change_rank" name="change_rank">Change customer rank</button>
</form>
</div>

{% endblock %}

bank/templates/bank/index-employee.html
{% extends "bank/base.html" %} {% block content %}
<!-- <ul>
  <li>Username: {{ user.username }}</li>
  <li>Phone number: {{ user.profile.phone_number }}</li>
  <li>Rank: {{ user.profile.customer_rank }}</li>
  <li>Is staff?: {{ user.is_staff }}</li>
</ul> -->
<section id="index_employee" class="general_margin">
  <h1>Create customer</h1>
  <form action="{% url 'bank:employee_index' %}" method="POST">
    {% csrf_token %}
    <input type="text" name="user" placeholder="User Name" />
    <input type="email" name="email" placeholder="Email Address" />
    <input type="text" name="phone_number" placeholder="Phone number" />
    <input type="password" name="password" placeholder="Password" />
    <input type="password" name="confirm_password" placeholder="Confirm Password" />
    <button>Create customer</button>
  </form>
  <p>{{ message }}</p>
  <p>{{ error }}</p>
  <h2>All customers</h2>
  <ul>
      
    {% for customer in customers %}
    <a href="{% url 'bank:customer_details' customer.pk %}"><li>{{ customer.username }}</li></a>
    {% endfor %}
  </ul>
</section>
{% endblock %}

bank/templates/bank/index.html
{% extends "bank/base.html" %} {% block content %}
<section id="customer_index" class="general_margin">
  <h1>Welcome, {{ user.username }}</h1>
  <div class="customer_accounts">
    <h4>Your accounts</h4>

    {% if accounts %}
    <table>
      <tr>
        <th>Account Name</th>
        <th>Balance</th>
        <th>Account ID</th>
      </tr>

      {% for account in accounts %}
      <tr>
        <td><a href="{% url 'bank:account_details' account.pk %}">{{ account.account_name }}</a></td>
        <td>{{ account.balance }}</td>
        <td>{{ account.account_id }}</td>
      </tr>
      {% endfor %}
    </table>
    {% else %}
    <p>You have no accounts.</p>
    {% endif %}
  </div>
  <div class="create_account">
    <h4>Create a new account</h4>
    <form action="." method="POST">
      {% csrf_token %}
      <div class="flex">
        <input type="text" name="account_name" id="account_name" placeholder="Account name" />
        <button class="button" type="submit" name="create_account">Create account</button>
      </div>
    </form>
  </div>

  <div>
    <ul class="buttons-menu">
      {% if user.profile.customer_rank == 'silver' or user.profile.customer_rank == 'gold' %}
      <li><a class="button" href="{% url 'bank:loan' %}">Take a loan</a></li>
      {% endif %}
      <li><a class="button" href="{% url 'bank:transfer_money' %}">Transfer money</a></li>
    </ul>
  </div>

  <div id="scheduled_payments">
    <h4>Scheduled payments</h4>
    {% if scheduled_payments %}

    <table>
      <tr>
        <th>Scheduled Payment Title</th>
        <th>Created at</th>
        <th>From Account</th>
        <th>To Account</th>
        <th>Amount</th>
      </tr>
      {% for scheduled_payment in scheduled_payments %}
      <tr>
        <td>{{ scheduled_payment.title }}</td>
        <td>{{ scheduled_payment.created_at }}</td>
        <td>{{ scheduled_payment.from_account }}</td>
        <td>{{ scheduled_payment.to_account }}</td>
        <td>{{ scheduled_payment.amount }}</td>
      </tr>
      {% endfor %}
    </table>
  </div>
  {% else %}
  <p>You have no scheduled payments</p>
  {% endif%}
  <div class="add_scheduled_payment">
    <form action="." method="POST">
      <h2>Add a scheduled payment</h2>
      {% csrf_token %}

      <label for="scheduled_payment_title">Scheduled Payment Title</label>
      <input type="text" name="scheduled_payment_title" id="scheduled_payment_title" />

      <label for="scheduled_payment_amount">Amount</label>
      <input type="number" name="scheduled_payment_amount" id="scheduled_payment_amount" />

      <label for="sp_accounts">From account</label>
      <select name="sp_accounts" id="sp_accounts">
        {% for account in accounts %}
        <option value="{{ account.pk }}">{{ account.account_name }}</option>
        {% endfor %}
      </select>

      <label for="sp_accounts2">To account</label>
      <select name="sp_accounts2" id="sp_accounts2">
        {% for account in accounts %}
        <option value="{{ account.pk }}">{{ account.account_name }}</option>
        {% endfor %}
      </select>
      <label for="sp_text">Text for debit account</label>
      <input type="text" name="sp_text" id="sp_text" />

      <label for="sp_text2">Text for credit account</label>
      <input type="text" name="sp_text2" id="sp_text2" />

      <button class="button" type="submit" name="add_scheduled_payment">Add Scheduled Payment</button>
    </form>
  </div>
</section>

{% endblock %}

bank/templates/bank/internal-transfer.html
{% extends "bank/base.html" %} {% block content %}

<section id="customer_index" class="general_margin">

  <div class="tranfer-money-nav">
    <ul>
        <li><a class="button" href="{% url 'bank:index' %}">Go back</a></li>
    </ul>
  </div>  

    <div class="tranfer-money-nav">
        <ul>
            <li><a  href="{% url 'bank:transfer_money' %}">Transfer between own accounts</a></li>
            <li><a class="selected" href="#">Transfer to another person</a></li>
            <li><a href="{% url 'bank:bank_to_bank_transfer' %}">Transfer to another person in another bank</a></li>
        </ul>
    </div>
  
    <div class="internal_transfer_money">
      <form action="." method="POST">
        <h2>Transfer money internally</h2>
        {% csrf_token %}
        <label for="from_internal_account">From account</label>
        <select required name="from_internal_account" id="from_internal_account">
          {% for account in accounts %}
          <option value="{{ account.pk }}">{{ account.account_name }}</option>
          {% endfor %}
        </select>
  
        <label for="to_internal_account">Internal Account ID</label>
        <input required type="text" name="to_internal_account" id="to_internal_account" />
  
        <label for="internal_transfer_text">Text for debit account</label>
        <input required type="text" name="internal_transfer_text" id="internal_transfer_text" />
  
        <label for="internal_transfer_text2">Message for recipient</label>
        <input required type="text" name="internal_transfer_text2" id="internal_transfer_text2" />
  
        <label for="internal_transfer_amount">Transfer amount</label>
        <input required type="number" name="internal_transfer_amount" id="internal_transfer_amount" />
        <button class="button" type="submit" name="internal_transfer_money">Transfer money</button>
      </form>
      {% if error %} {{ error }} {% endif %}
    </div>
  
    
  </section>
  
  {% endblock %}
  

bank/templates/bank/loan.html
{% extends "bank/base.html" %} {% block content %}
<section id="customer_index" class="general_margin">
  <div class="tranfer-money-nav">
    <ul>
        <li><a class="button" href="{% url 'bank:index' %}">Go back</a></li>
    </ul>
</div>
    
  {% if user.profile.customer_rank == 'silver' or user.profile.customer_rank == 'gold' %}
  <div class="get_loan">
    <h2>Get loan</h2>
    <form action="." method="POST">
      {% csrf_token %}
      <input required type="text" name="loan_name" id="loan_name" placeholder="Loan name" />
      <input required type="text" name="loan_text" id="loan_text" placeholder="Loan text" />
      <input required type="text" name="loan_amount" id="loan_amount" placeholder="Loan amount" />
      <label for="accounts3">Account to credit</label>
      <select required name="accounts3" id="accounts3">
        {% for account in accounts %}
        <option value="{{ account.pk }}">{{ account.account_name }}</option>
        {% endfor %}
      </select>
      <button class="button" type="submit" name="make_loan">Get Loan</button>
    </form>
  </div>
  {% endif %}
  
</section>

{% endblock %}

bank/templates/bank/transfer-money.html
{% extends "bank/base.html" %} {% block content %}
<section id="customer_index" class="general_margin">
  <div class="tranfer-money-nav">
    <ul>
        <li><a class="button" href="{% url 'bank:index' %}">Go back</a></li>
    </ul>
  </div>  
 
  <div class="tranfer-money-nav">
      <ul>
          <li><a class="selected" href="#">Transfer between own accounts</a></li>
          <li><a href="{% url 'bank:internal_transfer' %}">Transfer to another person</a></li>
          <li><a href="{% url 'bank:bank_to_bank_transfer' %}">Transfer to another person in another bank</a></li>
      </ul>
  </div>
  
  <div class="transfer_money">
    <form action="." method="POST">
      <h2>Transfer money</h2>
      {% csrf_token %}
      <label for="accounts">From account</label>
      <select required name="accounts" id="accounts">
        {% for account in accounts %}
        <option value="{{ account.pk }}">{{ account.account_name }}</option>
        {% endfor %}
      </select>

      <label for="accounts2">To account</label>
      <select required name="accounts2" id="accounts2">
        {% for account in accounts %}
        <option value="{{ account.pk }}">{{ account.account_name }}</option>
        {% endfor %}
      </select>

      <label for="transfer_text">Text for debit account</label>
      <input required type="text" name="transfer_text" id="transfer_text" />

      <label for="transfer_text2">Text for credit account</label>
      <input required type="text" name="transfer_text2" id="transfer_text2" />
      <label for="transfer_amount">Transfer amount</label>
      <input required type="number" name="transfer_amount" id="transfer_amount" />
      <button class="button" type="submit" name="transfer_money">Transfer money</button>
    </form>
  </div>
  
</section>

{% endblock %}